# Generated by Django 3.0.5 on 2020-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200810_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='moved_by_perm_sec1',
            new_name='moved_to_perm_sec_political',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='moved_by_ssg',
            new_name='moved_to_sec',
        ),
        migrations.RemoveField(
            model_name='file',
            name='moved_by_perm_sec2',
        ),
    ]
